In [6]:
import numpy as np

In [10]:
# Write a Python program to print the NumPy version in your system.
np.version.version

'1.19.2'

In [14]:
# Write a Python program to reverse an array (first element becomes last).
arr=np.arange(1,10)
# arr

arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [16]:
# Write a Python program to convert a list and tuple into arrays.
lst = [1,2,3,4]
np.array(lst)
tup=((1,2),(3,4),(5,6))
np.array(tup)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
# Write a Python program to find common values between two arrays.

arr1=np.arange(1,9)
arr2=np.array([1,2])
coms = np.intersect1d(arr1,arr2)
coms

array([1, 2])

In [22]:
# Write a Python program compare two arrays using numpy.
arr1=np.array([1,2,3,4,5])
arr2=np.array([5,6,7,8,9])
arr1==arr2

array([False, False, False, False, False])

In [26]:
# Write a Python program to change the dimension of an array.
arr1=np.array([[1,2,3,4],
             [4,5,6,7]])
arr1.shape
arr1.shape=4,2
print(arr1)

[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [33]:
#Write a Python program (using numpy) to sum of all the multiples of 3 or 5 below 100.
arr1=np.arange(1,100)
mul =arr1 [(arr1 % 3 == 0 ) | (arr1%5 ==0)]
mul.sum()


2318

In [40]:
# Write a Python program to convert a NumPy array into Python list structure.

#1D example
arr=np.arange(1,10)
arr.tolist()
#2D example
twodarr = np.array([[11, 12, 5, 2], [15, 6,10,100], [10, 8, 12, 5], [12,15,8,6]])
twodarr.tolist()

[[11, 12, 5, 2], [15, 6, 10, 100], [10, 8, 12, 5], [12, 15, 8, 6]]

In [45]:
# Write a Python program to how to add an extra column to a numpy array.
arr1 = np.array([[10,9,40],
                 [45,6,70],
                 [90,24,8]])
arr2=np.array([[10],
             [20],
              [30]])
np.append(arr1,arr2,axis = 1)

array([[10,  9, 40, 10],
       [45,  6, 70, 20],
       [90, 24,  8, 30]])

In [48]:
# Write a Python program to check whether the numpy array is empty or not.
arr1 = np.array([[10,9,40],
                 [45,6,70],
                 [90,24,8]])
arr2=np.array([])

arr1.size
arr2.size

if (arr1.size ==0):
    print('Array1 is empty')
if(arr2.size == 0):
    print('Arr2 is empty')

Arr2 is empty


In [50]:
# Write a Python program to normalize a 3x3 random matrix.

np.random.rand(3,3)

array([[0.68326639, 0.64276062, 0.18003629],
       [0.00844872, 0.68231745, 0.39683517],
       [0.28223225, 0.97879977, 0.64263197]])

In [51]:
# How to ignore all numpy warnings (not recommended)?
np.seterr(all='ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [70]:
# How to swap two rows of an array?
arr1=np.arange(0,10).reshape(5,2)
print(arr1)
print(arr1[[0, 2]])
arr1[[0, 2]] = arr1[[2, 0]]
arr1

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1]
 [4 5]]


array([[4, 5],
       [2, 3],
       [0, 1],
       [6, 7],
       [8, 9]])

In [ ]:
#  Compute bootstrapped 95% confidence intervals for the mean of a 
# 1D array X (i.e., resample the elements of an array with replacement N times, compute the
# mean of each sample, and then compute percentiles over the means).

#Assignment doubt question

In [72]:
# Python program to create a random vector of size 10 and sort it.
import numpy as np
randvect = np.random.random(10)
randvect.sort()
randvect

array([0.12683197, 0.14280121, 0.19192438, 0.23999626, 0.24615113,
       0.38692681, 0.48932738, 0.50711446, 0.63376902, 0.95538641])

In [77]:
# Write a Python program to check two random arrays are equal or not.
arr1=np.random.randint(1,10,5)
arr1
arr2=np.random.randint(1,20,5)
arr2
array_equal = np.allclose(arr1,arr2)
print(array_equal)

False


In [79]:
# Write a Python program to add, subtract, multiply, divide arguments element-wise.
print(np.add(1.2,1.3))
print(np.multiply(2.3,6.7))
print(np.divide(6,3))
print(np.subtract(10,5))

2.5
15.409999999999998
2.0
5


In [82]:
# Write a Python program to get the dates of yesterday, today and tomorrow.
yesterday = np.datetime64('today','D')-np.timedelta64(1,'D')
tomorrow = np.datetime64('today','D')+np.timedelta64(1,'D')
today = np.datetime64('today','D')
print('yesterday',yesterday)
print('tomorrow',tomorrow)
print('today',today)

yesterday 2021-02-13
tomorrow 2021-02-15
today 2021-02-14
